check50:
  files: &check50_files
    - !exclude "*"
    - !include "*.py"
    - !require hello.py
  checks:
    hello.py exists:
      exists: hello.py
    hello world:
      - run: python3 hello.py
        stdout: Hello, world!
        exit: 0
submit50:
  files: *check50_files
